### ISSUE TITLE
Fatal Error In Loading Formats or Codecs

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Video-Transcoder#11]
**Basically the entire site is bricked by this right now, and cannot properly build**

```[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
codecs (1:7)
1: {"H264":{"name":"H.264","compressionRange":{"min":1,"max":51},"ffmpegLib":"libx264"},"MPEG4":{"name":"MPEG-4","compressionRange":{"min":1,"max":31},"ffmpegLib":"libxvid","notSupported":true},"WINDOWS":{"name":"Windows Media Video","compressionRange":{"min":1,"max":51},"ffmpegLib":"wmv2"}}
          ^
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:213:30)
    at Module.error (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:15196:16)
    at tryParse (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:15083:23)
    at Module.setSource (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:15487:30)
    at ModuleLoader.addModuleSource (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:17519:20)
    at ModuleLoader.fetchModule (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:17586:9)
    at /home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:17549:36
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:17587:9)
    at /home/cryogenic/ffmpeg-wasm/Video-Transcoder/node_modules/rollup/dist/shared/rollup.js:17549:36```

**Comment by zackradisic** [comment]
Fixed https://github.com/Mozilla-Open-Lab-Etwas/Video-Transcoder-Codecs-Formats/commit/442968fe311e2e99b97404d8e8aeb9b3ace9c93e
